export const ALL_ITEMS_REQUEST = "ALL_ITEMS_REQUEST"
export const ALL_ITEMS_SUCCES = "ALL_ITEMS_SUCCES"
export const ALL_ITEMS_FAIL ="ALL_ITEMS_FAIL"
export const ITEM_DETAILS_REQUEST="ITEM_DETAILS_REQUEST"
export const ITEM_DETAILS_SUCCESS="ITEM_DETAILS_SUCCESS"
export const ITEM_DETAILS_FAIL="ITEM_DETAILS_FAIL"

export const FIX_ERRORS = "FIX_ERRORS"